name: Release - Tag
on:
  workflow_call:
    outputs:
      version:
        description: "The release version"
        value: ${{ jobs.create-release.outputs.version }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git - Checkout
        uses: actions/checkout@v3

      - name: Env variables - Main
        if: github.ref == 'refs/heads/main'
        run: |
          echo "DRY_RUN=false" >> $GITHUB_ENV
      - name: Env variables - Non-main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "DRY_RUN=true" >> $GITHUB_ENV

      - name: Create release
        id: release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          tag_prefix: ""
          dry_run: ${{ env.DRY_RUN }}