name: Release - Tag
on:
  workflow_call:
    outputs:
      version:
        description: "The release version"
        value: ${{ jobs.create-release.outputs.version }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semvers.outputs.minor }}
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Version - Get previous
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Version - Get next
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Version - Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.minor }}
          name: ${{ steps.semvers.outputs.v_minor }}
          draft: false
          prerelease: false